spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bd_rmsoft?useSSL=false
        username: root
        password: mysql

    jpa:
        show-sql: false 
        hibernate:
            ddl-auto: update
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect